# Generated by Django 3.1.7 on 2021-03-31 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 31, 18, 23, 2, 902934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
